services:
  sms_bundle.sms:
    class: Akenlab\SMSBundle\SMSEngine\SMSEngine
    arguments: [ '@service_container' ]
  app.exception_listener:
    class: Akenlab\SMSBundle\EventListener\NumberStateListener
    arguments: [ '@sms_bundle.sms' ]
    tags:
      - { name: kernel.event_listener, event: workflow.numbers_state.leave, method: leave }
      - { name: kernel.event_listener, event: workflow.numbers_state.enter, method: enter }
