<?php

namespace SMSBundle\Repository;

/**
 * InboundMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboundMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
