<?php

namespace SMSBundle\Repository;

/**
 * NumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberRepository extends \Doctrine\ORM\EntityRepository
{
}
