<?php

namespace Akenlab\SMSBundle\Repository;

/**
 * NumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberRepository extends \Doctrine\ORM\EntityRepository
{
	public function findWithState(array $allowedStates){
		if(count($allowedStates)){
			$qb = $this->createQueryBuilder('n');
			return $qb 	-> where($qb->expr()->in('n.state',':states'))
			    		-> setParameter('states', $allowedStates)
			 			-> getQuery()
			 			-> getResult();
		}else{
			return $this->findAll();
		}
	}
}
